version: '3'
services:
  app:
    container_name: scalable-backend-2
    build:
      context: .
      dockerfile: Dockerfile
    image: my-custom-backend:latest
    ports:
      - '3333:3333'
    environment:
      - MONGO_URI=mongodb://mongo:27017/scalable-backend
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data

volumes:
  mongo-data:
  redis-data:
