version: '3'
services:
  app:
    container_name: scalable-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3333:3333'
    environment:
      - MONGO_URI=mongodb://mongo:27017/scalable-backend
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - '27017:27017'
